package api

import (
	"context"
	"dev/github-fav-language/api/github_api/handler"
	"dev/github-fav-language/clients/github"
	"fmt"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/recover"
	// // docs are generated by Swag CLI, you have to import them.
	// // replace with your own docs folder, usually
	// _ "github.com/luna-protocol/ascent/docs/static/api" // revive:disable-line:staticcheck
)

type Server struct {
	app          *fiber.App
	GithubClient github.Client
}

func NewServer(githubClient github.Client) *Server {
	return &Server{
		GithubClient: githubClient,
	}
}

// StartAndListen
// @title Ascent API
// @version 1.0
// @description Ascent API powers Rec Financing
// @host localhost:3030
// @BasePath /
func (s *Server) StartAndListen(ctx context.Context) {
	// Fiber App
	app := fiber.New()
	s.app = app

	// This will recover from panics anywhere in the stack
	app.Use(recover.New(
		recover.Config{
			EnableStackTrace: true,
		},
	))
	app.Use(cors.New())

	v1group := app.Group("/v1")
	// Register Handlers
	_ = handler.NewHandler(v1group, s.GithubClient)

	err := app.Listen(fmt.Sprintf(":%d", 8000)) // TODO: add port to config s.Config.APIPort
	if err != nil {
		fmt.Printf("Failed to start/stop API: %v", err)
	}
}

func (s *Server) Shutdown() {
	if s.app != nil {
		_ = s.app.Shutdown()
	}
}
