package api

import (
	"context"
	"dev/github-fav-language/api/github_api/handler"
	"dev/github-fav-language/clients/github"
	"fmt"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/recover"

	// docs are generated by Swag CLI, you have to import them.
	// replace with your own docs folder, usually
	_ "dev/github-fav-language/docs/static/api"

	"github.com/gofiber/swagger"
)

type Server struct {
	app          *fiber.App
	GithubClient github.Client
}

func NewServer(githubClient github.Client) *Server {
	return &Server{
		GithubClient: githubClient,
	}
}

// StartAndListen
// @title Ascent API
// @version 1.0
// @description GITHub User Fav Language API
// @host localhost:8000
// @BasePath /
func (s *Server) StartAndListen(ctx context.Context) {
	// Fiber App
	app := fiber.New()
	s.app = app

	// This will recover from panics anywhere in the stack
	app.Use(recover.New(
		recover.Config{
			EnableStackTrace: true,
		},
	))
	app.Use(cors.New())

	// Register Handlers
	app.Get("/swagger/*", swagger.HandlerDefault)
	v1group := app.Group("/v1")
	_ = handler.NewHandler(v1group, s.GithubClient)

	err := app.Listen(fmt.Sprintf("0.0.0.0:%d", 8000)) // TODO: add port to config s.Config.APIPort
	if err != nil {
		fmt.Printf("Failed to start/stop API: %v", err)
	}
}

func (s *Server) Shutdown() {
	if s.app != nil {
		_ = s.app.Shutdown()
	}
}
